#elementos da Página
btn_signIn="xpath:.//a[@title='Log in to your customer account']"
txt_endereco_email="name:email"
txt_senha="name:passwd"
btn_entrar="id:SubmitLogin"
btn_contato="id:contact-link"
titulo_assunto="name:id_contact"
email_contato="id:email"
referencia_pedido="id:id_order"
btn_escolher_arquivo="id:uniform-fileUpload"
upload_arquivo="id:fileUpload"
campo_mensagem="id:message"
btn_enviar="id:submitMessage"
Mensagem_Sucesso="xpath:.//p[contains(normalize-space(.), 'Your message has been successfully sent to our team.')]"
btn_submeter="name:submitMessage"
procurar="id=search_query_top"
cliquelupa="name:submit_search"
mais_vendidos="xpath:.//a[@title='View a top sellers products']"
produto_escolhido="css:a.product-name"
adicionar_produto="xpath:(.//label[contains(., 'Quantity')]/following::i)[2]"
carrinho="id=add_to_cart"
fazerCheckout="css:a.btn.btn-default.button.button-medium"
AdicionarMaisUmProduto="css:i.icon-plus"
fazerCheckoutCompra="css:a.button.btn.btn-default.standard-checkout.button-medium"
comentario="css:textarea.form-control"
RealizarCheckout="css:button.button.btn.btn-default.button-medium"
CheckBoxEnvio="id:cgv"
RealizarCheckoutEnvio="css:button.button.btn.btn-default.standard-checkout.button-medium"
ValidarEnvio="xpath:.//h1[contains(., 'Shipping')]"
FormaPagamento="css:a.bankwire"
ConfirmarPagamento="css:button.button.btn.btn-default.button-medium"



